---
- name: Update packages on all Linux servers
  hosts: all
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Update package cache and upgrade all packages
      ansible.builtin.package:
        name: '*'
        state: latest
        update_cache: yes
      register: update_result
      retries: 3
      delay: 5
      until: update_result is success

    - name: Check if reboot is required (Red Hat-based systems)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_rhel
      when: ansible_os_family == 'RedHat'

    - name: Check if reboot is required (Ubuntu-based systems)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_ubuntu
      when: ansible_os_family == 'Debian'

    - name: Notify if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required on this server."
      when: >
        (ansible_os_family == 'RedHat' and reboot_required_rhel.stat.exists) or
        (ansible_os_family == 'Debian' and reboot_required_ubuntu.stat.exists)
---
